### PR TITLE
remove code from old cli namespaces

### PR DESCRIPTION
**Pull request by gilesknap**
Just removed a couple of things that are holdevers from the 'dev' namespace.

In particular I'm looking at changing the container names e.g.
- ioc-pmac-linux-runtime to
- ioc-pmac-linux-x86_64-runtime

And was just checking their are no refs to container name in this CLI.

### CODE REVIEW

**Comment by gilesknap** [comment]
@marcelldls please sanity check this.

**Comment by marcelldls** [comment]
Do I understand correctly that the build functionality is to be owned by IBEK?

Can we delete some of the uncalled code such as `repo2registry`? Also I think some of the globals like `IOC_NAME` are also no longer used?

```
(python3.11) [esq51579@pc0146 edge-containers-cli]$ vulture src/
src/edge_containers_cli/_version.py:13: unused variable 'version_tuple' (60% confidence)
src/edge_containers_cli/_version.py:16: unused variable 'version_tuple' (60% confidence)
src/edge_containers_cli/cmds/cli.py:178: unused function 'instances' (60% confidence)
src/edge_containers_cli/cmds/cli.py:294: unused function 'validate' (60% confidence)
src/edge_containers_cli/cmds/k8s_commands.py:75: unused attribute 'service_type' (60% confidence)
src/edge_containers_cli/cmds/local_commands.py:76: unused variable 'ioc_path' (60% confidence)
src/edge_containers_cli/docker.py:17: unused variable 'IMAGE_TAG' (60% confidence)
src/edge_containers_cli/git.py:18: unused function 'get_git_name' (60% confidence)
src/edge_containers_cli/git.py:42: unused function 'repo2registry' (60% confidence)
src/edge_containers_cli/globals.py:25: unused variable 'IOC_START' (60% confidence)
src/edge_containers_cli/globals.py:27: unused variable 'IOC_NAME' (60% confidence)
src/edge_containers_cli/utils.py:106: unused function 'normalize_tag' (60% confidence)
```

I may be wrong but is `IOC_CONFIG_FOLDER = "/epics/ioc/config/"` the only thing that is epics specific?

**Comment by gilesknap** [comment]
@marcelldls the build functionality is really absorbed into the developer container and the ./build file in each generic IOC.

I'm pretty sure you are right about the remaining redundant features. I like he look of `vulture`!

**Comment by gilesknap** [comment]
OK you inspired me to delete lots more.
```bash

# vulture src                                                                                                                                                                                 [13:00:56]
src/edge_containers_cli/_version.py:13: unused variable 'version_tuple' (60% confidence)
src/edge_containers_cli/_version.py:16: unused variable 'version_tuple' (60% confidence)
src/edge_containers_cli/cmds/cli.py:41: unused function 'env' (60% confidence)
src/edge_containers_cli/cmds/cli.py:178: unused function 'instances' (60% confidence)
src/edge_containers_cli/cmds/cli.py:294: unused function 'validate' (60% confidence)
```

**Comment by gilesknap** [comment]
I also think we should get rid of `validate` as we do this in CI in a much cleaner way now.
I'm a bit conflicted because it is nice to have a local check - just that it is quite different to what CI does not.

**Comment by gilesknap** [comment]
@marcelldls I broke a system test! Good thing we have those then.

Please can you investigate

**Comment by marcelldls** [comment]
> @marcelldls I broke a system test! Good thing we have those then.
> 
> Please can you investigate

See #110

**Comment by marcelldls** [comment]
> OK you inspired me to delete lots more.
> 
> ```shell
> # vulture src                                                                                                                                                                                 [13:00:56]
> src/edge_containers_cli/_version.py:13: unused variable 'version_tuple' (60% confidence)
> src/edge_containers_cli/_version.py:16: unused variable 'version_tuple' (60% confidence)
> src/edge_containers_cli/cmds/cli.py:41: unused function 'env' (60% confidence)
> src/edge_containers_cli/cmds/cli.py:178: unused function 'instances' (60% confidence)
> src/edge_containers_cli/cmds/cli.py:294: unused function 'validate' (60% confidence)
> ```

Looks neat!

**Comment by marcelldls** [comment]
> I also think we should get rid of `validate` as we do this in CI in a much cleaner way now. I'm a bit conflicted because it is nice to have a local check - just that it is quite different to what CI does not.

Why not update the validate command to use the new approach?

**Comment by gilesknap** [comment]
> Why not update the validate command to use the new approach?

Yes that makes sense!

**Pull request merged**
