### PR TITLE
Change enable to act on root app

### PR DESCRIPTION
**Pull request by marcelldls**
Change patch of enable to be on the root app. This allows ec to work with ec-helm-charts 4.0.0+b1 which aims to have enabled recorded in the git repo.
Question:
- Should this be `ec stop <service> --temp`? (with the git backend pushing changes to enabled being a default)
- Should we allow this at all - Because the patch sits on top of what is in the repo so we need to revert if you want to track the repo again. It has some benefits though for not relying on "the internet" and speed (directly communicate with argocd rather than git + sync argocd) + reducing number of commits added to the deployment repo

### CODE REVIEW

**Comment by marcelldls** [comment]
We can identify patches to params exposed to the root app using the roots app values.yaml by comparing the source manifests `argocd app manifests <ns>/<rootApp>` and the live state `argocd app get <ns>/<rootApp> -o yaml`

**Comment by gilesknap** [comment]
I'm getting the feeling that the concept of temporary vs permanent stop is over complicated.

I think that if we support ec making changes to the repo we should probably drop overrides to avoid confusion.

**Comment by marcelldls** [comment]
@gilesknap Are you willing to try demo this? I have tried it against an auto-synced and non auto-synced app-of-apps

**Comment by gilesknap** [comment]
Sure. Let's discuss tomorrow

**Comment by marcelldls** [comment]
@gilesknap Working against https://github.com/epics-containers/p47-deployment with the discussed helm chart changes captured in https://github.com/epics-containers/ec-helm-charts/pull/33 under a beta release

**Comment by marcelldls** [comment]
@gilesknap Ready - Please review against p47 and ec-helm-charts

**Comment by gilesknap** [comment]
I just want to record here that we have discussed the `--temp` feature and:
- it is good that the default is to update the repo as this keeps a record of beamline state
- but we do need `--temp` for when the git server is offline
- reporting that you can try `--temp` when trying to update the repo makes this temp feature discoverable
- we do need to work out what to do about authN though
  - maybe not give scientists write access to the repo - particularly because that involves fiddly config
  - using a web version of ec could mitigate this
  - but then perhaps we still need a way to supply --temp from the web UI for when the git server is offline?

**Comment by gilesknap** [comment]
I'm seeing an issue with running this against p47:
```

hgv27681@pc0116: /scratch/hgv27681/work/p47-deployment main
$ ec ps                                                                                                                                                                                   [10:30:11]
| name              | version         | ready | deployed             |
|-------------------|-----------------|-------|----------------------|
| bl47p-ea-dcam-01  | 2024.9.1        | false | 2024-09-16T20:18:08Z |
| bl47p-ea-dcam-02  | feature-branch2 | true  | 2024-09-16T20:18:08Z |
| bl47p-ea-panda-01 | 2024.9.1        | true  | 2024-09-16T20:18:07Z |
| bl47p-ea-test-01  | 2024.9.1        | true  | 2024-09-16T20:18:08Z |
| bl47p-mo-ioc-01   | 2024.9.1        | true  | 2024-10-03T08:28:46Z |
| p47-ea-test-01    | 2024.8.5        | true  | 2024-10-03T08:32:01Z |
(venv)  
hgv27681@pc0116: /scratch/hgv27681/work/p47-deployment main
$ ec stop bl47p-ea-dcam-02                                                                                                                                                                [10:30:21]
╭──────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────╮
│ /scratch/hgv27681/work/edge-containers-cli/src/edge_containers_cli/cli.py:258 in stop                                                                                                             │
│                                                                                                                                                                                                   │
│   255 ):                                                                                                                                                                                          │
│   256 │   """Stop a service"""                                                                                                                                                                    │
│   257 │   try:                                                                                                                                                                                    │
│ ❱ 258 │   │   backend.commands.stop(service_name, temp)                                                                                                                                           │
│   259 │   except GitError as e:                                                                                                                                                                   │
│   260 │   │   msg = f"{str(e)} - Try ec stop <service> --temp to bypass the git server"                                                                                                           │
│   261 │   │   raise GitError(msg) from e                                                                                                                                                          │
│                                                                                                                                                                                                   │
│ /scratch/hgv27681/work/edge-containers-cli/src/edge_containers_cli/cmds/argo_commands.py:99 in stop                                                                                               │
│                                                                                                                                                                                                   │
│    96 │   │   if temp:                                                                                                                                                                            │
│    97 │   │   │   patch_value(self.target, f"services.{service_name}.enabled", False)                                                                                                             │
│    98 │   │   else:                                                                                                                                                                               │
│ ❱  99 │   │   │   push_value(self.target, f"services.{service_name}.enabled", False)                                                                                                              │
│   100 │                                                                                                                                                                                           │
│   101 │   def _get_logs(self, service_name, prev) -> str:                                                                                                                                         │
│   102 │   │   namespace, app = extract_ns_app(self.target)                                                                                                                                        │
│                                                                                                                                                                                                   │
│ /scratch/hgv27681/work/edge-containers-cli/src/edge_containers_cli/cmds/argo_commands.py:42 in push_value                                                                                         │
│                                                                                                                                                                                                   │
│    39 │   repo_url = app_dicts["spec"]["source"]["repoURL"]                                                                                                                                       │
│    40 │   path = Path(app_dicts["spec"]["source"]["path"])                                                                                                                                        │
│    41 │                                                                                                                                                                                           │
│ ❱  42 │   set_values(                                                                                                                                                                             │
│    43 │   │   repo_url,                                                                                                                                                                           │
│    44 │   │   path / "values.yaml",                                                                                                                                                               │
│    45 │   │   key,                                                                                                                                                                                │
│                                                                                                                                                                                                   │
│ /scratch/hgv27681/work/edge-containers-cli/src/edge_containers_cli/git.py:34 in set_values                                                                                                        │
│                                                                                                                                                                                                   │
│    31 │   │   │   │   if value_repo == value:                                                                                                                                                     │
│    32 │   │   │   │   │   log.debug(f"{key} already set as {value}")                                                                                                                              │
│    33 │   │   │   │   else:                                                                                                                                                                       │
│ ❱  34 │   │   │   │   │   file_data.set_key(key, value)                                                                                                                                           │
│    35 │   │   │   │   │   file_data.dump_file()                                                                                                                                                   │
│    36 │   │   │   │   │                                                                                                                                                                           │
│    37 │   │   │   │   │   commit_msg = f"Set {key}={value} in {file}"                                                                                                                             │
│                                                                                                                                                                                                   │
│ /scratch/hgv27681/work/edge-containers-cli/src/edge_containers_cli/utils.py:149 in set_key                                                                                                        │
│                                                                                                                                                                                                   │
│   146 │   │   for key in keys:                                                                                                                                                                    │
│   147 │   │   │   if key is element:                                                                                                                                                              │
│   148 │   │   │   │   break  # Keep dict as pointer                                                                                                                                               │
│ ❱ 149 │   │   │   curser = curser[key]                                                                                                                                                            │
│   150 │   │                                                                                                                                                                                       │
│   151 │   │   # Set element if exists or create it                                                                                                                                                │
│   152 │   │   try:                                                                                                                                                                                │
│                                                                                                                                                                                                   │
│ /scratch/hgv27681/work/edge-containers-cli/venv/lib/python3.11/site-packages/ruamel/yaml/comments.py:853 in __getitem__                                                                           │
│                                                                                                                                                                                                   │
│    850 │                                                                                                                                                                                          │
│    851 │   def __getitem__(self, key: Any) -> Any:                                                                                                                                                │
│    852 │   │   try:                                                                                                                                                                               │
│ ❱  853 │   │   │   return ordereddict.__getitem__(self, key)                                                                                                                                      │
│    854 │   │   except KeyError:                                                                                                                                                                   │
│    855 │   │   │   for merged in getattr(self, merge_attrib, []):                                                                                                                                 │
│    856 │   │   │   │   if key in merged[1]:                                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'bl47p-ea-dcam-02'
(venv) FAIL

hgv27681@pc0116: /scratch/hgv27681/work/p47-deployment main
$                                                                                                                                                                                         [10:31:05]
```

**Comment by gilesknap** [comment]
I tried this and it looks all good.

And I like the comments in apps.yaml (I might add a linefeed before the first line of the ec_services comment?)

Lets merge and release!

**Pull request merged**
