### PR TITLE
Refactor for argocd

### PR DESCRIPTION
**Pull request by marcelldls**
Touch up front end:
- Use typer to handle env variables (Show in --help and do type casting/sanitising for things like export ENV_VARIABLE=false to read as boolean false)
- Dynamic command hiding based on chosen backend and commands implemented
- Consistant flow of user inputs for commands through backend rather than a mix of typer ctx, env reads, globals - to support validation, sanitising
- Separate frontend (typer) from backend (particular: error handling)
- Lazy import of monitor to reduce load time for everytime ec is called

Backend work:
- Remove docker ("local" backend) and related
- Implement an argocd backend
- Remove handling of symlink charts for helm commands and replace with shared helm values
- Allow changes to shared files to show as a new revision of a service
- Only interact with "ec-services" - These are statefulsets which are tagged "ec_service=true"
- Use custom errors over "typer error" so that targetted error handling can be done
- Add schema validation and type hinting for polars schemas to interface more clear
- Add tempfile context manager for file retension at debug and handle case of multiple temp files

### CODE REVIEW

**Comment by marcelldls** [comment]
After this is merged I will proceed with the change the name of the project to `ec-cli`

**Review by gilesknap — APPROVED** [review]
General
-----------

I just tried this out on my personal namespace and its working beautifully. Even the auto complete is now nippy. 

I also tried it against the argocd beamline p47 and all was good there too.

A couple of things:
- I'm not sure that we need a verification question for all deploy commands. Previouslyi had it only for deploy-local - open to discuss this.
- the services-template-helm and deployment-template-argocd both incorrectly set the graylog URL because that has changed. It needs to drop the '2' from graylog2.xxxxx
- the templates also need to put single quotes around the graylog URL otherwise zsh does not like it.

ArgoCD
-----------
I think this is working great as we originally specified. So great work.

However I'm feeling like it is a bit of a downgrade from helm. Things I don't like are:

- the ec_services flag means that I can't see things other than IOCs with ec - maybe we should review the enabled/removed discussion 
- loss of functionality - attach is a pretty important thing to have for an IOC and you need to go work out how to do that with kubectl

There is also an argument to say - let ec be for end users and let engineers know what they are doing and use kubectl. So if this argument wins out then we are already good to go (but maybe should also hobble the helm based one for consistency?)

**Comment by gilesknap** [comment]
Oh and I also tried it out on a k3s namespace.

I had issues that the PVCS were not getting created but that was nothing to do with you. So the helm template and ec work great for this use case too.

**Review by gilesknap — APPROVED** [review]
I trust your judgement on this one.

**Comment by marcelldls** [comment]
To clarify - Because we got rid of a lot of the complexity of the "local backend", the system tests no longer did very much & also started feeling over engineered with the minikube action

**Pull request merged**
