### PR TITLE
deploy-local override entrypoint with sleep

### PR DESCRIPTION
**Pull request by marcelldls**
Requires https://github.com/epics-containers/ec-helm-charts/pull/15

### CODE REVIEW

**Review by gilesknap — COMMENTED** [review]
Does this PR require a change to the helm chart?

All looks good.

**Comment by marcelldls** [comment]
> Does this PR require a change to the helm chart?
> 
> All looks good.

Yes, the proposed change is linked. Although I think its fair to say the default values (entry point in this case) have not been done the same as the rest of our parameters - where we have set the defaults in the chart values.yaml - and not the template like I have done here.

I feel like the required entrys in the beamline shared values.yaml should be the things that are beamline specific. Perhaps key-values pairs like `iocFolder: /epics/ioc` should have defaults set in the ioc-instance template. In this way they are still override-able but its not required per beamline

**Comment by marcelldls** [comment]
> > Does this PR require a change to the helm chart?
> > All looks good.
> 
> Yes, the proposed change is linked. Although I think its fair to say the default values (entry point in this case) have not been done the same as the rest of our parameters - where we have set the defaults in the chart values.yaml - and not the template like I have done here.
> 
> I feel like the required entrys in the beamline shared values.yaml should be the things that are beamline specific. Perhaps key-values pairs like `iocFolder: /epics/ioc` should have defaults set in the ioc-instance template. In this way they are still override-able but its not required per beamline



> > Does this PR require a change to the helm chart?
> > All looks good.
> 
> Yes, the proposed change is linked. Although I think its fair to say the default values (entry point in this case) have not been done the same as the rest of our parameters - where we have set the defaults in the chart values.yaml - and not the template like I have done here.
> 
> I feel like the required entrys in the beamline shared values.yaml should be the things that are beamline specific. Perhaps key-values pairs like `iocFolder: /epics/ioc` should have defaults set in the ioc-instance template. In this way they are still override-able but its not required per beamline

There might be something strange happening. When I read the Helm documentation, it seems that the subchart values.yaml should be the default - however - when I tried this then these values were ignored. This is why I ended up putting it in the template

@gilesknap should this not be flat?
https://github.com/epics-containers/ec-helm-charts/blob/4328ce6e933a7cd60e97747085f18e998991384d/Charts/ioc-instance/values.yaml#L1-L8

**Comment by marcelldls** [comment]
We have decided to fix the issue by allowing override through exposing of the entry point in the sub chart

**Pull request closed without merging**
