### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by gilesknap**
This refactors the code into a fashion that is more appropriate for adding an interactive TUI.

- A new base class Commands provides the common command implementations.
- K8sCommands derives from the above and provides K8S specific implementations.
- LocalCommands derives from Commands and provides local docker/podman implementations.
- These classes are initialized with context that is constant like namespace but not with any other args
- Monitor is now given a Command object so it can call the functions in blissful ignorance of the underlying implementation.
- global exception handling is added to the typer cli and will report if a function is not implemented for the current environment.

Frankly, I wrote this inside out initially and this is how it should have been done.
The unit tests were a great help in making these changes.

### CODE REVIEW

**Comment by gilesknap** [comment]
@OCopping We have a really good test coverage on this project. Do you know of any way of adding tests for the Monitor code so we can keep that quality bar high?

**Review by OCopping — APPROVED** [review]
Looks good to me!

**Comment by gilesknap** [comment]
I'm going to merge this and release it - then @OCopping's TUI changes will go on top of main.

**Comment by gilesknap** [comment]
Ooops merged it into create_monitor. Will now do another PR into main.

**Pull request merged**
